services:
    php-httpd:
        image: 192.168.30.219:5000/sysadmin/simars-php-apache2:0
        container_name: simars_app
        restart: always
        ports:
            - 80:80
        environment:
            - TZ=Asia/Jakarta
        volumes:
#sesuaikan dengan direktori di server hocker host
            - /home/xen/simars_web:/var/www/html
        networks:
            - macvlan_network
    cups:
        image: 192.168.30.219:5000/sysadmin/simars-cups:0
        container_name: cups
        restart: always
        ports:
            - 631:631
        devices:
            - /dev/bus/usb:/dev/bus/usb
        environment:
            - CUPSADMIN=print
            - CUPSPASSWORD=print
            - TZ=Asia/Jakarta
        volumes:
            - cups_data:/etc/cups
        networks:
            - macvlan_network

networks:
  macvlan_network:
    external: true

volumes:
    cups_data: